### ISSUE TITLE
The "Agenda" view is badly displaying events when the calendar macro is first loaded on the Month view

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-mocca-calendar#71] opened 2021-12-08 17:05 UTC
Steps to reproduce : 
* From MoccaCalendar.WebHome, create a couple of events in the upcoming days
* Go in the "Month" view
* Reload the page, you should see the upcoming events in the month view as such : 

<img width="921" alt="image" src="https://user-images.githubusercontent.com/5938943/145251155-0d410333-398b-4626-a65e-9c077111df72.png">

* Click on the "Agenda" tab, observe that the event names are not properly displayed

<img width="561" alt="image" src="https://user-images.githubusercontent.com/5938943/145251424-6327aa64-3ced-4643-acf0-8cd3ea87cdd3.png">

* Now reload the page, you should get automatically to the "Agenda" tab
* Click on the "Month" view then click again on the "Agenda" view, observe that the events are properly displayed this time

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5938943/145251566-26347c5e-f390-4f92-adcb-6d7d0ce2fcd1.png">

This seems linked to https://github.com/xwikisas/application-mocca-calendar/blob/e6c0926ed40de225c8a56c9899a91d43217ce06c/application-mocca-calendar-ui/src/main/resources/MoccaCalendar/JSONService.xml#L183 which prevents the month view to properly load the HTML of the events to be displayed in the Agenda viewer.

**Comment by ClemensRobbenhaar** [comment] 2021-12-12 15:50
This happens because the new version of the fullcalendar js lib does no longer notify via callback if a view is switched. Indeed removing the check for the ``outputView`` parameter fixes the issue.

**Comment by ClemensRobbenhaar** [comment] 2021-12-12 16:14
Oh, I forgot: fixed with commit 47d363d4 from my ``ckr-merge-upstream`` branch for version 2.11

**Comment by ClemensRobbenhaar** [comment] 2021-12-15 15:38
Still reproducible in 2.11-rc-1 however. Not sure if I can fix it for 2.11

**Comment by ClemensRobbenhaar** [comment] 2021-12-15 21:27
Actually I misunderstood the report that it was not fixed. The issue reported as still present was #72 instead.

**Closed by ClemensRobbenhaar** 2021-12-15 21:27 UTC
Labels: Type: Bug
