### ISSUE TITLE
Calendar missing sometimes when accessing the App

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-mocca-calendar#76] opened 2021-12-16 13:17 UTC
Preconditions: Have a calendar with some events created.

Steps to reproduce:

1. Access the Calendar App

Expected results: The Calendar appears with the created events.

Actual results: Sometimes the Calendar doesn't appear. In the browser console:

`require.min.js?r=1:5 Uncaught Error: Load timeout for modules: fullcalendar,moment/min/moment.min
https://requirejs.org/docs/errors.html#timeout
    at makeError (require.min.js?r=1:5)
    at R (require.min.js?r=1:5)
    at require.min.js?r=1:5`

![146378585-bef98a25-9ce3-4cc9-8a60-1cd5d9525688](https://user-images.githubusercontent.com/657716/146581085-f50a9745-dd06-40c2-9700-8c1e4f680bc3.jpg)

NOTE: After many reloads/refresh the Calendar appears.

Environment: Windows 10, XWiki 13.10 with MySQL 8.0 and XWiki 13.4.5, Calendar Application (Pro) 2.11-rc-1, Chrome 69

**Comment by lucaa** [comment] 2021-12-20 11:08
I cannot reproduce this issue on my side.

The cause seems to be a timeout upon loading the javascript libraries for calendar, this _may_ be related to a server that is (temporarily) slow or a (temporarily) slow internet connexion... @ane-gabriela you managed to reproduce this at different moments in time, in different days or at different times or it happened for a period and then it stopped?

**Comment by ane-gabriela** [comment] 2021-12-20 11:15
I could reproduce this issue on Local instance too. It happens from time to time when I access the calendars.


![LocalInstance](https://user-images.githubusercontent.com/40691112/146758633-1389b428-2deb-441f-8b19-3b50911fec15.jpg)

**Comment by lucaa** [comment] 2021-12-20 16:25
> I could reproduce this issue on Local instance too. It happens from time to time when I access the calendars.

so there may be something making the generation / rendering of that javascript slow, next time this happens it would be interesting to check how slow it actually is (by going in the network tab and checking the time it actually took to load). 

moment.js is a coming from a webjar, just as fullcalendar that timesout in the screenshot from the original issue description. the question is whether there could be anything on the XWiki server side that may make webjars take a long time to be served from the server.

**Comment by ane-gabriela** [comment] 2021-12-20 16:38
![Console1](https://user-images.githubusercontent.com/40691112/146800886-0fc2c6b8-2252-449b-81de-8a2ea3c0b91f.jpg)

![Network](https://user-images.githubusercontent.com/40691112/146800899-f9edc943-7342-46c8-9f45-d49c6505716f.jpg)

![Network1](https://user-images.githubusercontent.com/40691112/146801298-8b7af557-7a69-4477-a1a8-c184eff7f297.jpg)

![Network2](https://user-images.githubusercontent.com/40691112/146801295-f916832f-7c82-48a5-a4ee-3b672f1fe340.jpg)

![Network3](https://user-images.githubusercontent.com/40691112/146801289-09eb71f5-b06f-4d03-bb52-addef548b9d5.jpg)

**Comment by tmortagne** [comment] 2022-04-04 12:11
I often have reports of this problem, but it seems to happen way more often on Chrome than on Firefox.

**Comment by mflorea** [comment] 2022-04-16 09:04
Fixed in the fullcalendar macro with https://jira.xwiki.org/browse/FULLCAL-69 .

**Closed by mflorea** 2022-04-16 09:04 UTC
Labels: Priority: Critical, Type: Bug
