### ISSUE TITLE
Calendar config not displayed to Admin user

### ISSUE THREAD

**Issue by ldubost** [xwikisas/application-mocca-calendar#73] opened 2021-12-10 14:06 UTC
When going to the new Calendar settings panel developed in #67 in admin to change the "show meetings" configuration, there is the following error:

![image](https://user-images.githubusercontent.com/652233/145586153-e0a74bbe-39ad-49e9-91bd-d124b42a7972.png)

However when clicking on the MoccaCalendar.Code.AdminSheet link you can there edit the setting

![image](https://user-images.githubusercontent.com/652233/145586295-053bd655-bf13-4e3c-860e-86eb73b36083.png)

It could be an issue because of the non editability of AdminSheet as it's part of a pro extension

**Comment by ClemensRobbenhaar** [comment] 2021-12-12 17:11
This looks like some odd permission problem. I cannot reproduce it in my development instance.
Is the problem present in a sub wiki or the mail wiki?

**Comment by ane-gabriela** [comment] 2021-12-15 12:40
Hello! I've also reproduce this issues using XWiki 13.10 and 13.4.5 as instance Admin on Main and Subwikis

![Administration](https://user-images.githubusercontent.com/40691112/146188129-59128c79-e192-4456-b260-74a8d71b42f8.jpg)

I think it's possibly the same issue as [XQA-360](https://jira.xwikisas.com/browse/XQA-360)

**Comment by mflorea** [comment] 2021-12-16 05:32
@ClemensRobbenhaar the administrator needs to have:
* **view** right on the page that has the ``ConfigurableClass`` in order to see the administration section listed in the administration menu -> this means you need to generate a license first if the administration section is provided by a licensed extension
* **edit** right on the page that has the ``ConfigurableClass`` in order to view (render) the administration section inside the administration -> this means you need to exclude the administration section from the license check because all pages provided by a licensed extensions have edit protection by default.

Take a look at the Antivirus Application for an example https://github.com/xwikisas/application-antivirus/blob/master/application-antivirus-ui/pom.xml#L38 .

I see that the page that holds the configuration, ``MoccaCalendar.Code.GlobalSettings``, is created on the fly (not included in the XAR) so you won't have to exclude it in the pom. Note that since you're going to exclude ``MoccaCalendar.Code.AdminSheet`` from license check and thus allow administrators to edit it, you should move the code to a different page that is protected by the license. So best is to have:

    <codeToExecute>{{include reference="MoccaCalendar.Code.AdminSheetCode" /}}</codeToExecute>

in ``MoccaCalendar.Code.AdminSheet``, where ``MoccaCalendar.Code.AdminSheetCode`` is protected. The main reason to protect the code is to reduce support costs.

**Comment by ClemensRobbenhaar** [comment] 2021-12-16 13:45
I tried to get it fixed along the given lines. However I am not sure if I did it right, so not closing it for now.

**Comment by mflorea** [comment] 2022-01-19 13:45
@ClemensRobbenhaar the ``ConfigurableClass`` object needs to remain on the ``AdminSheet`` page, because the page holding this object needs to be editable. ``AdminSheetCode`` should have only the code that is included in ``codeToExecute`` from ``AdminSheet``'s ``ConfigurableClass`` object.

Also, be careful about the ``scope`` property. The Calendar Application supports XWiki 11.10 ATM while the scope property has been introduce recently in https://jira.xwiki.org/browse/XWIKI-18723 (XWiki 13.7RC1). You should use the old ``configureGlobally`` property which is still supported in the latest version of XWiki.

**Comment by ClemensRobbenhaar** [comment] 2022-01-19 14:22
Ah, that is why the ``scope`` property sometimes worked and sometimes not.
I will try to fix both issues this evening.

**Comment by ClemensRobbenhaar** [comment] 2022-01-19 21:06
I fixed both the missing `configureGlobally` property and the XAR format.
About the location of the `XWiki.ConfigurableClass` object: I am not sure if the location of that object matters, as the object itself should not be edited by the users. The actual settings to be edited are stored (manually via some code in the `AdminSheetCode`) on the page `MoccaCalendar.Code.GlobalSettings`. This page is not included in the application, but created on demand.

**Comment by mflorea** [comment] 2022-01-20 12:17
@ClemensRobbenhaar the problem, AFAIK, is that the Administration Application which provides the ``XWiki.ConfigurableClass`` doesn't include the sections (i.e. pages with an ``XWiki.ConfigurableClass`` objects) that are not editable. So unfortunately the page holding the ``XWiki.ConfigurableClass`` object needs to be excluded for the license check. Which is why our best practice is to keep **only** the ``XWiki.ConfigurableClass`` object on that page, without the actual code of your administration section. This should go in a separate page, included in ``codeToExecute``.

**Comment by ClemensRobbenhaar** [comment] 2022-01-20 12:38
Ah, that explains why the section sometimes does not show up at all. I will move the `XWiki.ConfigurableClass` to a separate page which is marked as `<type>configuration</type>` or the like in the `pom.xml`.

**Comment by ClemensRobbenhaar** [comment] 2022-01-22 09:58
Moved the instance of the class to its own page `MoccaCalendar.Code.AdminSheetConfig`.
If someone else but me could test if that fixes the bug, I'd appreciate it.

**Comment by mflorea** [comment] 2022-01-23 20:38
I don't understand why you didn't put the ``XWiki.ConfigurableClass`` in the ``AdminSheet`` page. ATM you have 3 pages:

* ``AdminSheet`` just includes ``AdminSheetCode`` <- it's kind of useless
* ``AdminSheetCode`` holds the actual code of the administration section <- this is useful
* ``AdminSheetConfig`` holds the ``XWiki.ConfigurableClass`` and includes ``AdminSheet`` (BTW, it could include directly ``AdminSheetCode``) <- as long as it's not listed in ``xwiki.extension.licensing.excludedDocuments`` the page is not editable so the administration section is not accessible so you didn't fix the problem

My suggestion was to have just 2 pages:
* ``AdminSheet`` holds the ``XWiki.ConfigurableClass`` object and is listed in ``xwiki.extension.licensing.excludedDocuments`` (so that it becomes editable and thus accessible as an administration section). It also includes ``AdminSheetCode`` in the value of the ``codeToExecute`` property.
* ``AdminSheetCode`` holds the actual code of the administration section, included in the value ``codeToExecute`` property of ``XWiki.ConfigurableClass``.

**Comment by ane-gabriela** [comment] 2022-03-07 15:46
Issue still present (XWiki 13.10.3 Cloud)

![Admin](https://user-images.githubusercontent.com/40691112/157067719-a30a621a-9942-4c55-b970-a3fc129aff62.jpg)

**Comment by ClemensRobbenhaar** [comment] 2022-03-07 16:20
I just see in the code https://github.com/xwikisas/application-licensing/blob/master/application-licensing-licensor/application-licensing-licensor-api/src/main/java/com/xwiki/licensing/internal/enforcer/DefaultEntityLicenseManager.java#L126  that pages excluded from the license should be separated by comma. ^^ I used line breaks instead.

**Comment by mflorea** [comment] 2022-04-16 09:14
Seems to work fine in 2.11.1

**Closed by mflorea** 2022-04-16 09:14 UTC
Labels: Type: Bug
