### ISSUE TITLE
The calendar view is not displayed in XWiki 14.1+

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-mocca-calendar#80] opened 2022-03-17 12:47 UTC
Environment: Windows 11 Pro 64bit, Firefox 98, using an instance of XWiki 14.1 on Tomcat 9.0.59/ PostgreSQL 14 (tested also on XWiki 13.10.3 Jetty/HSQLDB) on Java 11 and Java 17 from Oracle with Calendar Application (Pro) 2.11 and 2.11.1-rc1

STEPS TO REPRODUCE
1. Go to Calendar home page
2. Observe the browser console
3. Click 'Create new event'
4. Observe the browser console as well

EXPECTED RESULTS
The event configuration section is displayed for the creation of the new event.

ACTUAL RESULTS
Nothing happens. 

When landing the first time on Calendar home page, the following errors are displayed in browser's console:

`GET http://localhost:1113/webjars/wiki:xwiki/momentjs/2.29.1/min/moment.min/min/moment.min.js
[[HTTP/1.1 404  350ms]]()`

and

`Uncaught Error: Script error for "moment/min/moment.min", needed by: moccaCalendar, moment-jdateformatparser, bootstrap-datetimepicker
https://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    onScriptError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    load http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    load http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    load http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    fetch http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    check http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    bind http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    each http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    bind http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    each http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    enable http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    init http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    s http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*req.nextTick< http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    s http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    requirejs http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    <anonymous> http://localhost:1113/bin/view/MoccaCalendar/:731`

When clicking on "+Create new event" button, the following error is displayed:

`Uncaught Error: Load timeout for modules: fullcalendar
https://requirejs.org/docs/errors.html#timeout
    makeError http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    setTimeout handler*R http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5
    d http://localhost:1113/webjars/wiki:xwiki/requirejs/2.3.6/require.min.js?r=1:5`

Note that #76 was reproduced as well.

![Moment min js_404_1](https://user-images.githubusercontent.com/32512703/158810676-5be5cb17-45e4-4bb8-a000-ba47e26441fb.png)

**Comment by ClemensRobbenhaar** [comment] 2022-03-17 15:46
Locally reproducible by me with the contrib-extension, too. URL to load the `moment.js`: instead of `/xwiki/webjars/wiki%3Axwiki/momentjs/2.29.1/min/moment.min/min/moment.min.js` should be `/xwiki/webjars/wiki%3Axwiki/momentjs/2.29.1/min/moment.min.js`.

**Comment by ClemensRobbenhaar** [comment] 2022-03-17 20:45
Issue not reproduces with XWiki 14.1. The moment.js is loaded from `/xwiki/webjars/wiki%3Axwiki/momentjs/2.29.1/min/moment.min.js` which is just where it is located. Looks like a platform change to me.

The URL to load the js from is computed as ` 'moment':  "$services.webjars.url('org.webjars:momentjs', '')" + 'min/moment.min'`

**Comment by ilieandriuta** [comment] 2022-03-18 12:11
The Mocca Calendar Macro also doesn't work, displaying the same stacktrace. However, I've reproduced also another stacktrace (both on XWiki 13.10.3 and 14.1, on Edge browser):

```
GET http://localhost:1314/xwiki/bin/view/P1/fullcalendar.js net::ERR_ABORTED 404 (Not Found)
Uncaught Error: Script error for "fullcalendar"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js?r=1:5:1795)
    at HTMLScriptElement.onScriptError (require.min.js?r=1:5:17084)

GET http://localhost:1314/xwiki/bin/view/P1/gcal.js net::ERR_ABORTED 404 (Not Found)
Uncaught Error: Script error for "gcal"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js?r=1:5:1795)
    at HTMLScriptElement.onScriptError (require.min.js?r=1:5:17084)
        
GET http://localhost:1314/xwiki/bin/view/P1/jqueryui.js net::ERR_ABORTED 404 (Not Found)
        
Uncaught Error: Script error for "jqueryui"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js?r=1:5:1795)
    at HTMLScriptElement.onScriptError (require.min.js?r=1:5:17084)
```

![jqueryui_js_error_13_10_3](https://user-images.githubusercontent.com/32512703/159000720-a0f7b864-4660-4306-906a-f9d8645a0097.png)

**Comment by mflorea** [comment] 2022-04-04 12:23
XWiki 14.1RC1 provides a global RequireJS configuration for moment.js (see https://jira.xwiki.org/browse/XWIKI-19427) which should be used. The problem is that the FullCalendar Macro is defining its own config https://github.com/xwiki-contrib/macro-fullcalendar/blob/macro-fullcalendar-pom-2.2.9/macro-fullcalendar-ui/src/main/resources/Calendar/FullCalendar.xml#L130 which probably conflicts with the global config from ``javascript.vm``. We need to release a new version of the FullCalendar Macro that defines the moment.js config only if it's not already defined, by wrapping the ``require.config()`` code in a:

```
if (require.toUrl('moment') === './moment') {
  // The 'moment' module is not configured.
  require.config({
    // Configure moment.js
    ...
  });
}
```

or maybe (more bullet proof):

```
if (require.toUrl('moment').indexOf('/webjars/') < 0) {
  ...
}
```

**Comment by mflorea** [comment] 2022-04-15 10:45
Fixed in the Fullcalendar macro (upgraded to version 2.2.10).

**Closed by mflorea** 2022-04-15 10:45 UTC
Labels: Priority: Blocker, Type: Bug
