### ISSUE TITLE
Extra day is included in an all day event when created by selecting a section of the calendar

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-mocca-calendar#55] opened 2020-11-26 15:02 UTC
The calendar macro displays a calendar and allows to create events by operating the calendar (selecting a section of the displayed calendar pops up the event creation modal).

However, when selecting a couple of full days on the calendar (in month view, for example, or on the top of the week view), the event that gets created is one day longer than the selected period.

Steps:

1. select a piece of the calendar in month mode (e.g. a full week):

![image](https://user-images.githubusercontent.com/657716/100365962-7a9a5500-3000-11eb-800a-08322f109b81.png)

2. when the mouse is released, the "add event" popup is displayed:

![image](https://user-images.githubusercontent.com/657716/100366044-9e5d9b00-3000-11eb-94f1-d90f3c997006.png)

3. fill in title and description (optional), save

4. the result is an event that is 1 day longer than the selected period:

![image](https://user-images.githubusercontent.com/657716/100366120-bc2b0000-3000-11eb-9e41-b73b3dab6831.png)

**Comment by lucaa** [comment] 2020-11-26 15:03
Indeed the event period can be edited in the "add new event" popup, but the fact that it adds one extra day out of the box is a little misleading...

**Comment by acotiuga** [comment] 2021-01-11 18:41
According to https://fullcalendar.io/docs/select-callback, the **end** date is **exclusive** and it should be treated as such. However, there is this demo presented in the same documentation page to https://fullcalendar.io/docs/date-clicking-selecting-demo, where, unfortunately, the end date is anything else but excluded.
Given the fact that on a selection, the event form fills the date inputs with dates at midnight, one option would be to decrease the end date with 1 second obtaining the following result:
![selectingEvent](https://user-images.githubusercontent.com/8121819/104224180-47dfdb00-544d-11eb-9bcc-390a8d2bbb91.png)
![modalEvent](https://user-images.githubusercontent.com/8121819/104223981-04856c80-544d-11eb-8580-72c3876d6f60.png)
![calendarEvent](https://user-images.githubusercontent.com/8121819/104224007-0b13e400-544d-11eb-8c94-6ed7826af2e4.png)

**Comment by acotiuga** [comment] 2021-01-14 10:08
Reopen the issue for some more investigation:
Why the calendar is not producing the same event before(previewed event) and after(generated event) filling the event form?

**Comment by acotiuga** [comment] 2021-01-14 11:28
In the end, the problem is caused by bad handling of the `allDay` flag. When multiple days are selected and the flag is enabled, the events are marked as all day events and displayed in the all day events sections (when looking on weekly mode of the calendar). 
The consequence in this case is that the flag enabled means that the last day, which should be excluded, will actually be included.
On the other hand, if the flag is not enabled, the event will look like an event spanned on the entire day/s, without being added in the all day events section, even if it takes from one day at the midnight to another day at midnight.
A clear view of the differences in the 2 cases is in the following weekly events image:
![Screenshot from 2021-01-14 13-21-32](https://user-images.githubusercontent.com/8121819/104584995-142ecc00-566c-11eb-8341-5960928c9889.png)

**Comment by acotiuga** [comment] 2021-01-14 11:29
This can be reduced to a problem of `allDay` flag handling.

**Comment by acotiuga** [comment] 2021-01-15 18:49
Closing this issue with the solution that consists of removing a workaround for a fullcalendar.io issue that was fixed in the newest version. https://github.com/fullcalendar/fullcalendar/issues/2909 can be checked for more details.
Note: 549c4969b87c1258df17fc6a7913c3fef4d54bab is the only commit that fixes this issue(rest of commits were reverted).

**Closed by acotiuga** 2021-01-15 18:49 UTC
Labels: Priority: Major, Type: Bug

**Comment by lucaa** [comment] 2021-02-23 22:40
> Note: [549c496](https://github.com/xwikisas/application-mocca-calendar/commit/549c4969b87c1258df17fc6a7913c3fef4d54bab) is the only commit that fixes this issue(rest of commits were reverted).

@acotiuga you mean d8fbfcf , I assume, 549c496 was reverted or is it 549c496 that was not supposed to be reverted?

**Comment by acotiuga** [comment] 2021-02-24 09:23
@lucaa you are right, https://github.com/xwikisas/application-mocca-calendar/commit/d8fbfcf385c133342fa1dd286bf500cce61d92f3 holds the fix for this issue. It was a mention that the rest should be ignored by any interested dev. In addition, being the last one, there was no reason to consider  https://github.com/xwikisas/application-mocca-calendar/commit/d8fbfcf385c133342fa1dd286bf500cce61d92f3 as reverted.
Thanks!
